### ISSUE TITLE
Trouble running HS on Spikeinterface

### ISSUE THREAD

**Issue by nasnass** [mhhennig/HS2#65]
Hi!
I am having a bit of difficulties getting HS to run using Spike interface. This is the error I am getting:

The extractor was not dumpable
Error running herdingspikes
Traceback (most recent call last):
  File "C:\Users\nasya\anaconda3\envs\herdingspikes\lib\site-packages\spikeinterface\sorters\basesorter.py", line 200, in run_from_folder
    SorterClass._run_from_folder(output_folder, sorter_params, verbose)
  File "C:\Users\nasya\anaconda3\envs\herdingspikes\lib\site-packages\spikeinterface\sorters\herdingspikes\herdingspikes.py", line 170, in _run_from_folder
    recording = st.normalize_by_quantile(
  File "C:\Users\nasya\anaconda3\envs\herdingspikes\lib\site-packages\spikeinterface\toolkit\preprocessing\normalize_scale.py", line 196, in normalize_by_quantile
    return NormalizeByQuantileRecording(*args, **kwargs)
  File "C:\Users\nasya\anaconda3\envs\herdingspikes\lib\site-packages\spikeinterface\toolkit\preprocessing\normalize_scale.py", line 60, in __init__
    random_data = get_random_data_chunks(recording, **random_chunk_kwargs)
  File "C:\Users\nasya\anaconda3\envs\herdingspikes\lib\site-packages\spikeinterface\toolkit\utils.py", line 36, in get_random_data_chunks
    for segment_index in range(recording.get_num_segments()):
AttributeError: 'NoneType' object has no attribute 'get_num_segments'

Here is how I am running it:

sorting_HS = ss.run_herdingspikes(recording, output_folder='results_HS', filter=False, verbose=True)

Whenever I try to pre-process it, and then run the sorter, the Kernel dies. 

recording_f = st.bandpass_filter(recording, freq_min=100, freq_max=3000)
recording = recording_f.save(format='binary')

I have only take a small chunk of my data (not even 1GB) just to try and get it to work. Would be very thankful for any hints!

**Comment by BptGrm** [comment]
From your log it seems that the issue comes from SpikeInterface's preprocessing, have you tried submitting the problem to them ?

**Comment by nasnass** [comment]
Just submitted it - thank you for the fast reply! I will comment the solution and close the issue here when I figure out what the problem is.

**Comment by nasnass** [comment]
Sadly not

**Comment by mhhennig** [comment]
Can you run another sorter? It indeed looks like there is something wrong with the extractor, as pointed out by @BptGrm.
