### ISSUE TITLE
HS on Spike Interface

### ISSUE THREAD

**Issue by Zoe0793** [mhhennig/HS2#67]
Hello, 
I want to run HS2 on spike interface but receive the following error: 

Traceback (most recent call last):
```
  File "C:\Users\Analysis\Documents\Code\SI_094\test_095.py", line 312, in <module>
    sorting_HS = ss.run_sorter('herdingspikes', recording2Sort, output_folder=r'C:\Users\Analysis\Documents\Code\SpikeInterface95\results_HS', verbose=True)
  File "C:\Users\Analysis\anaconda3\envs\si_env_094\lib\site-packages\spikeinterface\sorters\runsorter.py", line 142, in run_sorter
    return run_sorter_local(**common_kwargs)
  File "C:\Users\Analysis\anaconda3\envs\si_env_094\lib\site-packages\spikeinterface\sorters\runsorter.py", line 157, in run_sorter_local
    output_folder = SorterClass.initialize_folder(
  File "C:\Users\Analysis\anaconda3\envs\si_env_094\lib\site-packages\spikeinterface\sorters\basesorter.py", line 101, in initialize_folder
    if not cls.is_installed():
  File "C:\Users\Analysis\anaconda3\envs\si_env_094\lib\site-packages\spikeinterface\sorters\herdingspikes\herdingspikes.py", line 128, in is_installed
    import herdingspikes as hs
  File "C:\Users\Analysis\anaconda3\envs\si_env_094\lib\site-packages\herdingspikes\__init__.py", line 4, in <module>
    from herdingspikes.hs2 import HSDetection, HSClustering
  File "C:\Users\Analysis\anaconda3\envs\si_env_094\lib\site-packages\herdingspikes\hs2.py", line 7, in <module>
    from .detection_localisation.detect import detectData
  File "herdingspikes/detection_localisation/detect.pyx", line 1, in init herdingspikes.detection_localisation.detect
    # distutils: language = c++
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

Can you help with this? 
Thanks, 
Zoe

**Comment by Zoe0793** [comment]
Fixed it by installing numpy 1.22. (newer version was incompatible with SI 0.95 and numpy 1.21 installed by default)
